#!/usr/bin/env python3
"""
UCTalent referral link automation.

The job page has a "Refer & Earn" button that opens a modal containing a
per-job referral link plus a copy control. This module drives that flow with
no clicking from the user:

  1. click the "Refer & Earn" BUTTON
  2. wait for the modal to render the link
  3. read the link straight out of the DOM  (primary, most reliable)
  4. copy it to the clipboard

Site facts this is built around (read from the UCTalent frontend, not guessed):

* The button label comes from i18n key `pages/job-detail → ui.quickPanel.referEarn`
  and it carries no aria-label or data-testid, so it can only be matched by
  text. Only `en` and `vi` locales exist, and `getEffectiveLocale()` defaults to
  "vi" — there is no language cookie and nothing persists it across reloads
  (it is decided per render, partly from IP). So we try both labels instead of
  trying to detect the language. Vietnamese is tried first because the site
  resolves to it by default.

* An `<a href="/refer-earn">` carries the same caption as the button and would
  navigate away from the job page, so only `<button>` elements are clicked.

* The link is generated by POST /jobs/:id/referral-links, not written into the
  page. It is displayed with CSS ellipsis, so we read the full textContent and
  pull the URL out with a regex.

* The modal header renders `ui.header.referringTo` followed by the job title in
  a **child <span>**. That span is a language-independent place to read which
  job the link belongs to, which matters because the referral URL is opaque and
  contains no job id.

* The copy control differs by build: deployed renders a button labelled
  `ui.referral.copyLink` ("Copy Link" / "Sao chép liên kết"), a newer build
  replaces it with a copy icon carrying aria-label="Copy referral link". Both
  are matched.

* An internal referrer shows `InternalReferrerBadge`, a `role="status"` box
  with hardcoded Vietnamese text, present in both languages. It is reported so
  a caller can tell a 100%-reward link from an external one.

Clipboard note: the site's copy calls navigator.clipboard.writeText, which
needs a real user gesture, so a synthetic click never updates the clipboard.
The link is therefore never read from the clipboard — if the copy does not
take, the value is written directly instead.
"""

import json
import os
import re
import sys
import io
import time
import unicodedata
from urllib.parse import urlparse

from chrome_utils import execute_js, poll_js, get_clipboard, set_clipboard, open_url_in_tab


# ─── Labels (Vietnamese first: the site resolves to "vi" by default) ─────────

# i18n key: pages/job-detail → ui.quickPanel.referEarn
LABEL_REFER = [
    "Giới thiệu và nhận thưởng",   # vi
    "Refer & Earn",                # en
]

# i18n key: pages/job-detail → ui.header.referringTo
LABEL_REFERRING_TO = [
    "Bạn đang giới thiệu ứng viên cho",   # vi
    "You're referring a candidate to",    # en
]

# i18n key: pages/job-detail → ui.referral.copyLink (only the deployed build)
LABEL_COPY_LINK = [
    "Sao chép liên kết",   # vi
    "Copy Link",           # en
]

# Newer build: a copy icon on the link box, not translated at all. Matched as
# a plain substring test in JS, so this is a pattern, not a regex.
COPY_ARIA_MATCHES = ("copy", "sao chép", "sao chep")

# The referral URL, for use inside a JS regex literal.
#
# The slashes MUST be escaped: an unescaped "//" inside /.../ terminates the
# literal, and the remainder gets parsed as JavaScript. A character class of
# "cannot be a real URL character" keeps the tail free of quoting problems.
URL_RE = r"https?:\/\/[a-z0-9.-]*uctalent\.io\/referral\/[^\s\"'<>\\]+"


# Characters that carry a stroke or a slash instead of a combining mark, so
# NFD leaves them alone. Vietnamese needs "đ" ("Bạn" would normalise to "ban
# ang" otherwise), the rest are here so a Latin-1 locale cannot break us.
_UNDECOMPOSABLE = str.maketrans({
    "đ": "d", "Đ": "d",
    "ø": "o", "Ø": "o",
    "æ": "ae", "Æ": "ae",
    "œ": "oe", "Œ": "oe",
    "ß": "ss",
    "ł": "l", "Ł": "l",
    "þ": "th", "Þ": "th",
    "ð": "d", "Ð": "d",
})


def normalise(text):
    """Lowercase, strip diacritics, drop punctuation, collapse whitespace.

    Must match the JS `norm()` below so labels compare equal on both sides.
    Diacritics are stripped so "Giới thiệu" and "Gioi thieu" compare equal,
    and punctuation is dropped so "Giới Thiệu Và Nhận Thưởng" (the title-cased
    duplicate MUI renders) matches "Giới thiệu và nhận thưởng".
    """
    if not text:
        return ""
    text = unicodedata.normalize("NFD", text.lower().translate(_UNDECOMPOSABLE))
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = re.sub(r"[^\w]+", " ", text, flags=re.ASCII)
    return re.sub(r"\s+", " ", text).strip()


# Shared JS helpers, embedded in every snippet so they agree on normalisation.
# Must stay in sync with normalise() above — "đ" has no combining mark, so
# normalise() maps it and norm() substitutes it.
_JS_NORM = """
    function norm(s) {
        return (s || '').toLowerCase()
            .replace(/[\\u0110\\u0111]/g, 'd')   // đ Đ
            .replace(/[\\u00f8\\u00d8]/g, 'o')   // ø Ø
            .replace(/[\\u00e6\\u00c6]/g, 'ae')  // æ Æ
            .replace(/[\\u0153\\u0152]/g, 'oe')  // œ Œ
            .replace(/\\u00df/g, 'ss')          // ß
            .replace(/[\\u0142\\u0141]/g, 'l')   // ł Ł
            .replace(/[\\u00fe\\u00de]/g, 'th')  // þ Þ
            .replace(/[\\u00f0\\u00d0]/g, 'd')   // ð Ð
            .normalize('NFD')
            .replace(/[\\u0300-\\u036f]/g, '')
            .replace(/[^a-z0-9]+/g, ' ')
            .replace(/\\s+/g, ' ').trim();
    }
"""

_JS_HELPERS = _JS_NORM + """

    // The referral URL, wherever the site decided to put it
    var URL_RE = /""" + URL_RE + """/i;

    function findLink(root) {
        var nodes = root.querySelectorAll('p,span,div,a,code');
        for (var i = 0; i < nodes.length; i++) {
            if (nodes[i].children.length > 0) { continue; }
            var t = (nodes[i].textContent || '').trim();
            if (t.toLowerCase().indexOf('uctalent.io/referral/') === -1) { continue; }
            var m = t.match(URL_RE);
            if (m) { return m[0]; }
        }
        return '';
    }

    // The job title, read from the child <span> the header renders next to
    // ui.header.referringTo. Language-independent on purpose.
    function findJobTitle(root) {
        var prefixes = TITLE_PREFIXES_NORM;
        var heads = root.querySelectorAll('div,h1,h2,h3,h4,h5,h6,p');
        for (var i = 0; i < heads.length; i++) {
            var span = heads[i].querySelector(':scope > span');
            if (!span) { continue; }
            var full = norm(heads[i].innerText);
            var isHeader = false;
            for (var k = 0; k < prefixes.length; k++) {
                if (full.indexOf(prefixes[k]) === 0) { isHeader = true; break; }
            }
            if (isHeader) {
                var title = (span.innerText || '').trim();
                if (title) { return title; }
            }
        }
        // Fallback: strip the prefix off the header text
        for (var j = 0; j < heads.length; j++) {
            var full2 = norm(heads[j].innerText);
            for (var p = 0; p < prefixes.length; p++) {
                if (full2.indexOf(prefixes[p]) === 0 && full2.length > prefixes[p].length) {
                    return heads[j].innerText.trim().slice(prefixes[p].length).trim();
                }
            }
        }
        return '';
    }

    // InternalReferrerBadge: role="status" with hardcoded Vietnamese text,
    // so it shows in both languages.
    function findInternal(root) {
        var els = root.querySelectorAll('[role="status"]');
        for (var i = 0; i < els.length; i++) {
            var t = (els[i].innerText || '').toLowerCase();
            if (t.indexOf('nhan 100') > -1 || t.indexOf('internal') > -1) { return true; }
        }
        return false;
    }

    // The referral modal, or null when it is not open
    function findModal() {
        var modals = document.querySelectorAll('.MuiModal-root');
        for (var m = 0; m < modals.length; m++) {
            if (findLink(modals[m])) { return modals[m]; }
        }
        return null;
    }
""".replace("TITLE_PREFIXES_NORM", json.dumps([normalise(p) for p in LABEL_REFERRING_TO]))


# ─── JavaScript ──────────────────────────────────────────────────────────────

# Reads the modal: the link, the job it belongs to, whether the referrer is
# internal, and the locale the page is actually rendering in.
JS_READ_REFERRAL = ("(function() {" + _JS_HELPERS + """
    var modal = findModal();
    var root = modal || document;
    return JSON.stringify({
        link: findLink(root),
        jobTitle: findJobTitle(root),
        internal: findInternal(root),
        open: !!modal,
        lang: document.documentElement.lang || ''
    });
})()""")

# Clicks the "Refer & Earn" BUTTON, in any supported language.
_JS_CLICK_TAIL = """
    // Shared with JS_HAS_REFERRAL_BUTTON: first visible button whose label matches
    function find() {
        var all = document.querySelectorAll('button');
        for (var i = 0; i < all.length; i++) {
            var el = all[i];
            if (WANT.indexOf(norm(el.getAttribute('aria-label') || el.innerText)) === -1) { continue; }
            var r = el.getBoundingClientRect();
            // Skip the hidden responsive duplicates MUI renders
            if (r.width < 40 || r.height < 20) { continue; }
            return el;
        }
        return null;
    }
    var el = find();
    if (!el) { return 'not_found'; }
    el.scrollIntoView({ block: 'center' });
    ['mousedown', 'mouseup', 'click'].forEach(function(type) {
        el.dispatchEvent(new MouseEvent(type, {
            bubbles: true, cancelable: true, view: window, button: 0
        }));
    });
    return 'clicked';
})()"""

JS_CLICK_REFERRAL = (
    "(function() {\n    var WANT = __WANT__;\n" + _JS_NORM + _JS_CLICK_TAIL
).replace("__WANT__", json.dumps([normalise(x) for x in LABEL_REFER]))

# True once the Refer & Earn button is on screen (it renders after the SPA loads).
_JS_HAS_BTN_TAIL = """
    var all = document.querySelectorAll('button');
    for (var i = 0; i < all.length; i++) {
        var el = all[i];
        if (WANT.indexOf(norm(el.getAttribute('aria-label') || el.innerText)) === -1) { continue; }
        var r = el.getBoundingClientRect();
        if (r.width >= 40 && r.height >= 20) { return 'found'; }
    }
    return '';
})()"""

JS_HAS_REFERRAL_BUTTON = (
    "(function() {\n    var WANT = __WANT__;\n" + _JS_NORM + _JS_HAS_BTN_TAIL
).replace("__WANT__", json.dumps([normalise(x) for x in LABEL_REFER]))

# Clicks the copy control, whichever build rendered it.
JS_CLICK_COPY = ("(function() {" + _JS_HELPERS + """
    var root = findModal() || document;
    var WANT = __WANT_COPY__;
    // Newer build: aria-label on the link box, untranslated
    var ARIA = __WANT_ARIA__;
    var byAria = root.querySelectorAll('[aria-label]');
    for (var a = 0; a < byAria.length; a++) {
        var aria = (byAria[a].getAttribute('aria-label') || '').toLowerCase();
        var isCopy = false;
        for (var c = 0; c < ARIA.length; c++) {
            if (aria.indexOf(ARIA[c]) > -1) { isCopy = true; break; }
        }
        if (!isCopy) { continue; }
        var ra = byAria[a].getBoundingClientRect();
        if (ra.width < 40 || ra.height < 15) { continue; }
        byAria[a].click();
        return 'clicked';
    }
    // Deployed build: a button labelled with ui.referral.copyLink
    var all = root.querySelectorAll('button,[role="button"]');
    for (var i = 0; i < all.length; i++) {
        if (WANT.indexOf(norm(all[i].innerText)) === -1) { continue; }
        var r = all[i].getBoundingClientRect();
        if (r.width < 20 || r.height < 15) { continue; }
        all[i].click();
        return 'clicked';
    }
    return 'not_found';
})()""").replace("__WANT_COPY__", json.dumps([normalise(x) for x in LABEL_COPY_LINK])).replace(
    "__WANT_ARIA__", json.dumps(list(COPY_ARIA_MATCHES)))


# ─── Helpers ─────────────────────────────────────────────────────────────────

def _read_state():
    """Read the modal: {'link','jobTitle','internal','open','lang'}. Blanks if absent."""
    blank = {'link': '', 'jobTitle': '', 'internal': False, 'open': False, 'lang': ''}
    result = execute_js(JS_READ_REFERRAL, timeout=20)
    if not result or not isinstance(result, str):
        return blank
    try:
        data = json.loads(result)
    except json.JSONDecodeError:
        return blank
    return {
        'link': (data.get('link') or '').strip(),
        'jobTitle': (data.get('jobTitle') or '').strip(),
        'internal': bool(data.get('internal')),
        'open': bool(data.get('open')),
        'lang': (data.get('lang') or '').strip().lower(),
    }


def job_title_matches(modal_title, job_title):
    """True if the modal's link belongs to the job we asked about.

    The referral URL is opaque and holds no job id, so this is the only guard
    against saving another job's link. Both sides are normalised so accents,
    case and punctuation do not matter.
    """
    if not job_title:
        return True
    if not modal_title:
        return False
    got = normalise(modal_title)
    want = normalise(job_title)
    return got == want or want in got or got in want


def referrer_kind(link, internal_badge):
    """Classify the saved link: 'internal', 'external' or 'unknown'.

    utm_content carries the referrer type (see the frontend's
    job-referral-link.ts): recruiter/company_admin → "recruiter", and an
    internal referrer is confirmed by the badge. Older links saved before the
    Epic 5 format have no utm_content and were always attributed to a headhunter.
    """
    if not link:
        return 'unknown'
    try:
        query = urlparse(link).query
    except ValueError:
        query = ''
    if 'utm_content=recruiter' in query or internal_badge:
        return 'internal'
    if 'utm_content=' in query:
        return 'external'
    return 'legacy'


# ─── Main API ────────────────────────────────────────────────────────────────

def fetch_referral_link(job_title=None, timeout=30, verbose=True):
    """Click Refer & Earn, wait for the modal, return (link, info).

    The job detail page must already be open in the automation tab (call
    open_url_in_tab(job_url) first).

    Args:
        job_title:  job to confirm the modal belongs to. Pass it whenever you
                    have it — it is the only guard against saving a link that
                    belongs to a different job.
        timeout:    seconds to wait for the modal to render the link
        verbose:    print progress

    Returns:
        (link, info) where info is
            {'jobTitle': str, 'internal': bool, 'kind': str, 'language': str}
        or (None, info) if the link could not be obtained.
    """
    info = {'jobTitle': '', 'internal': False, 'kind': 'unknown', 'language': ''}
    state = _read_state()
    info['language'] = state['lang'] or 'unknown'

    # Modal may already be open with the right link (retry / user opened it)
    if not (state['link'] and job_title_matches(state['jobTitle'], job_title)):
        if verbose:
            print("  🔄 Clicking 'Refer & Earn'...")
        # The job page is a React SPA, so the button can render after load
        if not poll_js(JS_HAS_REFERRAL_BUTTON, timeout=15, interval=1.0):
            if verbose:
                print("  ⚠️  Could not find the 'Refer & Earn' button.")
                print("     Is the job page open and fully loaded? Are you signed in?")
                print("     Is the page in a language other than Vietnamese or English?")
            return None, info

        if execute_js(JS_CLICK_REFERRAL, timeout=20) != 'clicked':
            if verbose:
                print("  ⚠️  Could not click 'Refer & Earn'.")
            return None, info

        # The modal renders asynchronously, so poll instead of sleeping blindly
        if verbose:
            print("  ⏳ Waiting for the referral modal...")
        state = _wait_for_link(timeout)
        if not state:
            if verbose:
                print("  ⚠️  Modal did not show a referral link in time.")
            return None, info

    info['jobTitle'] = state['jobTitle']
    info['internal'] = state['internal']

    # Guard: a mismatch means the modal is stale or belongs to another job
    if job_title and not job_title_matches(state['jobTitle'], job_title):
        if verbose:
            print("  ⚠️  Modal is for a different job — refusing to save.")
            print(f"     Modal says: {state['jobTitle'] or '(title not readable)'}")
            print(f"     Expected:   {job_title}")
        return None, info

    link = state['link']
    info['kind'] = referrer_kind(link, state['internal'])

    # Click the copy control so the button behaves as the user expects. The
    # site's own copy cannot update the clipboard from a synthetic click, so we
    # make sure the clipboard ends up holding this link before reporting success.
    before = (get_clipboard() or '').strip()
    copied = execute_js(JS_CLICK_COPY, timeout=20)
    clip = before
    if copied == 'clicked':
        for _ in range(4):
            time.sleep(0.4)
            clip = (get_clipboard() or '').strip()
            if clip and clip != before:
                break

    if clip != link:
        if verbose:
            print("  ℹ️  Site's copy did not update the clipboard — copying it directly.")
        set_clipboard(link)

    if verbose:
        print(f"  ✅ Referral link captured ({len(link)} chars)")
        print(f"     {link}")
        print(f"     job: {state['jobTitle'] or '(not read)'}  [page lang: {info['language']}]")
        print(f"     referrer: {info['kind']}"
              + ("  (100% reward)" if info['kind'] == 'internal' else ""))
        if copied != 'clicked':
            print("  ℹ️  Copy control not found — link taken from the page.")

    return link, info


def _wait_for_link(timeout=30, step=1.0):
    """Poll the modal until a referral link shows up. Returns state or None."""
    waited = 0.0
    while waited < timeout:
        state = _read_state()
        if state['link']:
            return state
        time.sleep(step)
        waited += step
    return None


# ─── CLI (handy for testing) ────────────────────────────────────────────────

def _ensure_utf8():
    if hasattr(sys.stdout, 'reconfigure'):
        try:
            sys.stdout.reconfigure(encoding='utf-8')
        except Exception:
            pass


if __name__ == '__main__':
    _ensure_utf8()
    print("=" * 60)
    print("UCTalent referral link fetcher")
    print("=" * 60)

    url = sys.argv[1] if len(sys.argv) > 1 else None
    title = sys.argv[2] if len(sys.argv) > 2 else None

    if url:
        print(f"\nOpening: {url}")
        open_url_in_tab(url)
        time.sleep(6)

    got_link, got_info = fetch_referral_link(job_title=title)
    print()
    if got_link:
        print(f"RESULT: {got_link}")
        print(f"INFO:   {got_info}")
    else:
        print("RESULT: None — could not get the referral link.")